# railway.toml
[build]
builder = "RAILPACK"
watchPaths = ["**/*.py", "requirements.txt", ".github/workflows/*.yml"]

[deploy]
startCommand  = "python main.py"
restartPolicy = "ON_FAILURE"
maxRetries    = 10
healthcheckPath = "/healthz"

[service]
name   = "worker"
region = "eu-west"   # Amsterdam

[env]
TZ = "Europe/Athens"
SIGNALS_HTTP = "1"      # or rely on PORT via our auto-enable code
LOG_LEVEL = "INFO"
