name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Lint (flake8 with repo config)
      run: flake8 --config .flake8 .

    - name: Syntax check
      run: python -m py_compile main.py

    - name: Pytest (smoke)
      env:
        PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        TELEGRAM_BOT_TOKEN: ""
        TELEGRAM_CHAT_ID: ""
        WALLET_ADDRESS: "0x0000000000000000000000000000000000000000"
        ETHERSCAN_API: ""
        CRONOS_RPC_URL: ""
        TZ: "Europe/Athens"
      run: pytest -q
