name: CI (AST + tests) on PR
on:
  pull_request:
    branches: [ main ]
jobs:
  ast_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: AST parse all .py
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          for p in pathlib.Path(".").rglob("*.py"):
              if any(x in p.parts for x in (".venv","__pycache__")):
                  continue
              try:
                  ast.parse(p.read_text(encoding="utf-8"))
              except Exception as e:
                  bad.append((str(p), type(e).__name__, str(e)))
          if bad:
              for f, t, msg in bad:
                  print(f"[SYNTAX] {f}: {t}: {msg}")
              sys.exit(1)
          print("AST OK")
          PY
      - name: Run tests
        run: pytest -q
