name: CI (AST-only + Diagnostics)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ast_diag:
    name: AST check + verbose diagnostics
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run AST diagnostics
        run: |
          python scripts/ast_repair.py || true
      - name: Summary
        run: |
          echo "[CI] AST diagnostics completed at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
