name: CI (AST only)
on:
  pull_request:
    branches: [ main ]
jobs:
  ast_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: AST parse
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad = []
          for path in pathlib.Path(".").rglob("*.py"):
              if any(part in path.parts for part in (".venv", "__pycache__")):
                  continue
              try:
                  ast.parse(path.read_text(encoding="utf-8"))
              except Exception as exc:
                  bad.append((str(path), type(exc).__name__, str(exc)))
          if bad:
              for file_path, exc_type, message in bad:
                  print(f"[SYNTAX] {file_path}: {exc_type}: {message}")
              sys.exit(1)
          print("AST OK")
          PY
