name: CI (AST-only)
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  ast_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: AST Syntax Check
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          for p in pathlib.Path(".").rglob("*.py"):
              if any(x in p.parts for x in (".venv","__pycache__",".github")): continue
              try: ast.parse(p.read_text(encoding="utf-8"))
              except Exception as e: bad.append((str(p), type(e).__name__, str(e)))
          if bad:
              for f,t,m in bad:
                  print(f"[AST ERROR] {f}: {t}: {m}")
              sys.exit(1)
          print("✅ AST check passed")
          PY
      - name: Run Auto Repair (optional)
        run: |
          if [ -f scripts/ast_repair.py ]; then
            python scripts/ast_repair.py || true
          fi
