name: CI (AST only)
on:
  pull_request:
    branches: [ main ]
jobs:
  ast_only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
      - name: AST pre-repair sweep
        run: |
          python scripts/ast_repair.py || true
      - name: AST parse all .py (post-repair)
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          for p in pathlib.Path(".").rglob("*.py"):
              if any(x in p.parts for x in (".venv","__pycache__")):
                  continue
              try:
                  ast.parse(p.read_text(encoding="utf-8"))
              except Exception as e:
                  bad.append((str(p), type(e).__name__, str(e)))
          if bad:
              for f,t,msg in bad:
                  print(f"[SYNTAX] {f}: {t}: {msg}")
              sys.exit(1)
          print("AST OK")
          PY
