name: Cordex Diag (Ultra-lite + Debug)

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (best-effort)
        run: |
          python -V
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pipdeptree || true

      - name: Run Cordex Diag (never fail)
        continue-on-error: true
        env:
          TZ: ${{ secrets.TZ }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ETHERSCAN_API: ${{ secrets.ETHERSCAN_API }}
          RPC_URL: ${{ secrets.RPC_URL }}
          DEX_PAIRS: ${{ secrets.DEX_PAIRS }}
          PRICE_MOVE_THRESHOLD: ${{ secrets.PRICE_MOVE_THRESHOLD }}
          INTRADAY_HOURS: ${{ secrets.INTRADAY_HOURS }}
          EOD_TIME: ${{ secrets.EOD_TIME }}
        run: |
          set +e
          python scripts/cordex_diag.py --mask-secrets --try-import main.py core telegram reports utils || true
          # Αν δεν φτιάχτηκε, φτιάξε placeholder με timestamp + μικρό debug
          if [ ! -f diag_report.md ]; then
            echo "_No diag_report.md produced._" > diag_report.md
            echo "" >> diag_report.md
            echo "### Debug" >> diag_report.md
            echo "- Runner CWD: $(pwd)" >> diag_report.md
            echo "- Files in CWD:" >> diag_report.md
            ls -la >> diag_report.md
            echo "" >> diag_report.md
            echo "- Python:" >> diag_report.md
            python -V >> diag_report.md
            echo "" >> diag_report.md
            echo "- Exists scripts/cordex_diag.py ? $( [ -f scripts/cordex_diag.py ] && echo YES || echo NO )" >> diag_report.md
          fi
          # Γράψε έστω άδεια για τα υπόλοιπα αν λείπουν
          [ -f diag_report.json ]  || echo '{}' > diag_report.json
          [ -f diag_tree.txt ]     || echo "_No diag_tree.txt produced._" > diag_tree.txt
          [ -f diag_imports.log ]  || echo "_No diag_imports.log produced._" > diag_imports.log

      - name: Create/Update Issue "Cordex Diag — latest"
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const title = 'Cordex Diag — latest';
            function readOr(f, alt) {
              return fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : alt;
            }
            const md   = readOr('diag_report.md',   '_No diag_report.md produced._');
            const tree = readOr('diag_tree.txt',    '_No diag_tree.txt produced._');
            const imps = readOr('diag_imports.log', '_No diag_imports.log produced._');

            const body = `${md}

---
### diag_tree.txt (tail)
\`\`\`
${tree.split('\n').slice(-40).join('\n')}
\`\`\`

### diag_imports.log
\`\`\`
${imps}
\`\`\`
`;

            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            const { data: issues } = await github.rest.issues.listForRepo({
              owner, repo, state: 'open'
            });
            const existing = issues.find(i => i.title === title);

            let url;
            if (existing) {
              const { data } = await github.rest.issues.update({
                owner, repo, issue_number: existing.number, body
              });
              url = data.html_url;
            } else {
              const { data } = await github.rest.issues.create({
                owner, repo, title, body
              });
              url = data.html_url;
            }
            return url;

      - name: Show Issue link
        run: |
          echo "### Cordex Diag Issue" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.Create_Or_Update_Issue_Cordex_Diag_—_latest.outputs.result }}" >> "$GITHUB_STEP_SUMMARY" || true

      - name: Upload artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cordex-diag
          path: |
            diag_report.md
            diag_report.json
            diag_imports.log
            diag_tree.txt
          if-no-files-found: warn
