name: PR-011 Smoke (AST + Imports)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      DRY_RUN: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install minimal tooling
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi
      - name: AST check (no-exec)
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          errors=[]
          for f in pathlib.Path('.').rglob('*.py'):
              parts=set(f.parts)
              if any(x in parts for x in {'.venv','venv','build','dist','node_modules','.git','.github'}):
                  continue
              try: ast.parse(f.read_text(encoding='utf-8'), filename=str(f))
              except Exception as e: errors.append((str(f), repr(e)))
          if errors:
              for f,e in errors: print(f"[AST ERR] {f}: {e}")
              sys.exit(1)
          print("AST OK")
          PY
      - name: Imports smoke (no network)
        run: |
          python scripts/smoke.py
