name: PR-011 Smoke (DRY_RUN)
on:
  pull_request:
    branches: [ main ]
    paths:
      - "main.py"
      - ".github/workflows/pr011-smoke.yml"
      - "core/**"
      - "telegram/**"
      - "reports/**"
      - "utils/**"
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: AST sanity
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          for p in pathlib.Path(".").rglob("*.py"):
              if any(x in p.parts for x in (".venv","__pycache__")): continue
              try: ast.parse(p.read_text(encoding="utf-8"))
              except Exception as e: bad.append((str(p),type(e).__name__,str(e)))
          if bad:
              for f,t,m in bad: print(f"[SYNTAX] {f}: {t}: {m}")
              sys.exit(1)
          print("AST OK")
          PY
      - name: Run main.py with DRY_RUN=1
        env:
          DRY_RUN: "1"
          TZ: "Europe/Athens"
        run: |
          python main.py | tail -n 50
