name: PR-011 Smoke (AST-only)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ast_check:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: AST check (no imports, no exec)
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          skip={'.venv','venv','build','dist','node_modules','.git','.github'}
          for f in pathlib.Path('.').rglob('*.py'):
              if any(x in f.parts for x in skip):
                  continue
              try:
                  ast.parse(f.read_text(encoding='utf-8'), filename=str(f))
              except Exception as e:
                  bad.append((str(f), e))
          if bad:
              for f,e in bad:
                  print(f"[AST ERR] {f}: {e}")
              sys.exit(1)
          print("[AST] OK — all files parsed successfully.")
          PY

      - name: Marker
        run: echo "[SMOKE] PR-011 AST-only check completed."
