name: Repo Health Check
on: [push, pull_request]
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps (soft)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: Run repo health
        run: python scripts/repo_health.py || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: repo-health-report
          path: repo_health_report.txt
          if-no-files-found: ignore
