name: Repo Snapshot (artifact-only, no secrets)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Print HEAD info
        run: |
          echo "HEAD: $(git rev-parse --short HEAD)"
          echo "Branch: ${GITHUB_REF}"

      - name: Create tarball
        run: |
          SNAP="wallet_monitor_Dex_${GITHUB_SHA::7}.tar.gz"
          tar --exclude='.git' --exclude='.github' \
              --exclude='node_modules' --exclude='.venv' --exclude='venv' \
              -czf "${SNAP}" .
          echo "SNAP=${SNAP}" >> $GITHUB_ENV
          ls -lh "${SNAP}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-snapshot_${{ github.sha }}
          path: ${{ env.SNAP }}
          if-no-files-found: error
