name: runtime-smoke
on:
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Athens
      DRY_RUN: "1"
      DEBUG_HOLDINGS: "1"
      PYTHONPATH: "."
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: AST sanity
        run: |
          python - <<'PY'
          import ast, pathlib, sys
          bad=[]
          for p in pathlib.Path(".").rglob("*.py"):
              if any(x in p.parts for x in (".venv","__pycache__")): continue
              try: ast.parse(p.read_text(encoding="utf-8"))
              except Exception as e: bad.append((str(p),type(e).__name__,str(e)))
          if bad:
              for f,t,m in bad: print(f"[SYNTAX] {f}: {t}: {m}")
              sys.exit(1)
          print("AST OK")
          PY
      - name: Holdings diagnostics (if present)
        run: |
          if [ -f scripts/diag_holdings.py ]; then
            python scripts/diag_holdings.py || true
          else
            echo "diag_holdings.py not present — skipping"
          fi
      - name: Run main.py (DRY_RUN)
        run: |
          if [ -f main.py ]; then
            python main.py | tail -n 120
          else
            echo "main.py missing"
          fi
