name: Runtime Smoke
on:
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Import check (no side-effects)
        run: |
          python - <<'PY'
          import importlib, sys
          mods = [
            "main",
            "core.alerts","core.config","core.guards","core.holdings","core.pricing",
            "core.providers.cronos","core.providers.etherscan_like","core.rpc",
            "core.runtime_state","core.tz","core.wallet_monitor","core.watch",
            "reports.aggregates","reports.day_report","reports.ledger","reports.scheduler","reports.weekly",
            "telegram.api","telegram.commands","telegram.dispatcher","telegram.formatters","telegram.send",
          ]
          for m in mods:
              importlib.import_module(m)
          print("✅ Import pass without side-effects")
          PY
      - name: Run ping
        run: python scripts/cordex_ping.py
