name: Runtime Smoke (run main.py for 45s with timeout)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  runtime_smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      DRY_RUN: "1"          # ζητάμε “στεγνή” λειτουργία αν τη σέβεται το main.py
      PYTHONUNBUFFERED: "1"
      TZ: "Europe/Athens"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (best effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi

      - name: Run main.py with hard timeout (collect logs)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ci_logs
          # Το coreutils `timeout` υπάρχει στα runners. Τρέχουμε 45s και κόβουμε.
          # Exit κωδικός 124 = timeout: το θεωρούμε ΟΚ για smoke.
          set +e
          timeout 45s python main.py > ci_logs/runtime.log 2>&1
          code=$?
          set -e
          echo "Runtime exit code: $code" | tee ci_logs/exit_code.txt
          # Δεν σκοτώνουμε το job σε 124 (timeout) ή 0. Μόνο αν υπάρχει “άσχημο” exit.
          if [ "$code" != "0" ] && [ "$code" != "124" ]; then
            echo "::warning::main.py exited with non-zero code ($code). See artifact logs."
            # Δεν κάνουμε fail εδώ για να μη μπλοκάρει το main push — αλλά το βλέπεις στα logs.
          fi

      - name: Tail last 80 log lines (to build summary)
        run: |
          if [ -f ci_logs/runtime.log ]; then
            echo "----- LAST 80 LOG LINES -----"
            tail -n 80 ci_logs/runtime.log || true
          else
            echo "No runtime.log produced."
          fi

      - name: Upload runtime logs
        uses: actions/upload-artifact@v4
        with:
          name: runtime-smoke-logs_${{ github.sha }}
          path: ci_logs/
          if-no-files-found: warn
