name: Tests (matrix)

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * *'  # daily at 03:17 UTC

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Safe env
        run: |
          echo TZ=Europe/Athens >> $GITHUB_ENV
          echo CRONOS_RPC_URL= >> $GITHUB_ENV
          echo WALLET_ADDRESS= >> $GITHUB_ENV
          echo TELEGRAM_BOT_TOKEN= >> $GITHUB_ENV
          echo TELEGRAM_CHAT_ID= >> $GITHUB_ENV
          echo EOD_HOUR=23 >> $GITHUB_ENV
          echo EOD_MINUTE=55 >> $GITHUB_ENV
      - name: PyTest
        env:
          PYTHONPATH: .
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: pytest -q
